default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  user: postgres
  password: postgres
  min_messages: WARNING

development:
  <<: *default
  database: tunisia_open_data_back_development

test:
  <<: *default
  database: tunisia_open_data_back_test

production:
  <<: *default
  database: tunisia_open_data_back_production
  username: tunisia_open_data_back
  password: <%= ENV['TUNISIA_OPEN_DATA_BACK_DATABASE_PASSWORD'] %>
